import type { Metadata } from "next";
import "./globals.css";
import "./components/Header";
import HeaderComponent from "./components/Header";
import FooterComponent from "./components/Footer";
("./components/FooterComponent");

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="max-h-screen">
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
